name: highway_gpu
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - pytorch
  - pytorch-cuda=11.7
  - torchvision
  - torchaudio
  - x264=1!161.3030
  - tensorboard=2.12.0
  - pyvirtualdisplay
  - gym=0.21.0 
  - pip
  - pip:
      - highway_env==1.5
      - stable-baselines3==1.7
      - wandb
      - pygame
      - ffmpeg==1.4
    

